Repository cloudpilot-ai/karpenter-provider-gcp, pull requests merged in 2025-07, with the labels that each got.

#63 fix: fix image pull failure
  pkg/providers/instance/instance.go
Labels: bug

#64 fix: support e2-medium and other instance-type format like this
  pkg/providers/instancetype/types.go
Labels: bug, enhancement, lgtm

#65 fix: reduce long node deletion delay
  examples/nodepool/default-nodepool.yaml
  pkg/providers/instance/instance.go
  pkg/providers/metadata/utils.go
Labels: bug

#66 refactor: optimize instance retrieval by using cache-first approach and consolidating sync logic
  pkg/providers/instance/instance.go
Labels: cleanup

#73 feat: handle terminated/stopped ins
  cmd/controller/main.go
  pkg/controllers/controllers.go
  pkg/controllers/interruption/controller.go
  pkg/providers/instance/instance.go
Labels: enhancement

#76 feat: support configure cos image version
  charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
  examples/nodeclass/default-gcenodeclass.yaml
  examples/nodeclass/ubuntu-gcenodeclass.yaml
  pkg/apis/v1alpha1/gcenodeclass.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/imagefamily/containeroptimizedos.go
Labels: enhancement

#77 feat: support image id
  charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
  pkg/apis/v1alpha1/gcenodeclass.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/operator.go
  pkg/providers/imagefamily/containeroptimizedos.go
  pkg/providers/imagefamily/image.go
  pkg/providers/imagefamily/types.go
  pkg/providers/imagefamily/ubuntu.go
  pkg/providers/instance/instance.go
Labels: enhancement

#78 fix: throw error if the image not found
  pkg/providers/imagefamily/image.go
Labels: bug

#82 feat: support gpu
  pkg/providers/instancetype/types.go
Labels: enhancement

#83 chore: price provider cleanup
  pkg/controllers/providers/pricing/controller.go
  pkg/providers/pricing/pricing.go
  pkg/providers/pricing/pricing_test.go
Labels: cleanup

#89 fix: karpenter nodes not belongs to gke nodepool
  pkg/providers/instance/instance.go
  pkg/providers/metadata/utils.go
Labels: bug

#90 doc: update readme
  README.md
Labels: documentation

#92 cleanup: typo fix
  charts/README.md
Labels: cleanup

#97 fix: fix OOM and creation error when component restarted
  pkg/cache/unavailableofferings.go
  pkg/controllers/interruption/controller.go
  pkg/providers/instance/instance.go
  pkg/providers/instancetype/instancetype.go
Labels: bug

#102 fix: add clutser name labels to the vm created
  pkg/cloudprovider/cloudprovider.go
  pkg/providers/instance/instance.go
  pkg/utils/utils.go
Labels: bug, cleanup

#103 Add more control over gcp credentials in helm chart
  charts/karpenter/templates/deployment.yaml
  charts/karpenter/values.yaml
Labels: enhancement

#104 Adding option to use specified service account
  charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
  charts/karpenter/crds/karpenter.sh_nodeclaims.yaml
  charts/karpenter/crds/karpenter.sh_nodepools.yaml
  pkg/apis/v1alpha1/gcenodeclass.go
  pkg/operator/operator.go
  pkg/providers/instance/instance.go
Labels: enhancement
