Repository cloudpilot-ai/karpenter-provider-gcp, pull requests merged in 2025-08, with the labels that each got.

#108 Check if node is handled by karpenter, not just if it's in the cluster
  pkg/controllers/interruption/controller.go
Labels: bug

#106 fix(crd): correct schema for systemDisk category validation
  charts/karpenter/crds/karpenter.k8s.gcp_gcenodeclasses.yaml
  pkg/apis/v1alpha1/gcenodeclass.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
Labels: bug, lgtm

#114 fix: support gke specific zone labels
  pkg/operator/operator.go
Labels: bug

#112 Implement max pods configuration
  pkg/providers/instance/instance.go
  pkg/providers/metadata/utils.go
Labels: enhancement

#116 doc: make charts doc better
  charts/README.md
Labels: documentation

#119 cleanup: Remove redundant code
  examples/nodeclaim/default-nodeclaim.yaml
Labels: cleanup

#121 Update README.md
  README.md
Labels: documentation

#124 feat(helm): allow for specification of pull secrets
  charts/karpenter/templates/deployment.yaml
  charts/karpenter/values.yaml
Labels: enhancement

#126 feat/instance: add default cloud platform scopes to service accounts
  pkg/providers/instance/instance.go
Labels: enhancement
