Repository cloudpilot-ai/karpenter-provider-gcp, pull requests merged in 2025-04, with the labels that each got.

#24 feature: implement boilerplate Pricing provider code
  pkg/operator/operator.go
  pkg/providers/pricing/pricing.go
Labels: lgtm

#25 doc: add repo approvers and reviewers
  OWNERS
Labels: lgtm

#23 Add a contributing guide
  CONTRIBUTING.md
Labels: documentation, lgtm

#20 feature: implement InstanceType boilerplate code
  cmd/controller/main.go
  examples/crds/default-nodeclass.yaml
  go.mod
  go.sum
  pkg/cloudprovider/cloudprovider.go
  pkg/controllers/controllers.go
  pkg/controllers/providers/instancetype/controller.go
  pkg/operator/operator.go
  pkg/providers/instancetype/instancetype.go
  vendor/github.com/samber/lo/.travis.yml
  vendor/github.com/samber/lo/CHANGELOG.md
  vendor/github.com/samber/lo/Dockerfile
  vendor/github.com/samber/lo/LICENSE
  vendor/github.com/samber/lo/README.md
  vendor/github.com/samber/lo/channel.go
  vendor/github.com/samber/lo/errors.go
  vendor/github.com/samber/lo/find.go
  vendor/github.com/samber/lo/internal/rand/ordered_go118.go
  vendor/github.com/samber/lo/internal/rand/ordered_go122.go
  vendor/github.com/samber/lo/intersect.go
  vendor/github.com/samber/lo/map.go
  vendor/github.com/samber/lo/math.go
  vendor/github.com/samber/lo/mutable/slice.go
  vendor/github.com/samber/lo/parallel/slice.go
  vendor/github.com/samber/lo/retry.go
  vendor/github.com/samber/lo/slice.go
  vendor/github.com/samber/lo/string.go
  vendor/github.com/samber/lo/tuples.go
  vendor/github.com/samber/lo/type_manipulation.go
  vendor/modules.txt
Labels: enhancement

#27 doc: fix chapter layer
  CONTRIBUTING.md
Labels: documentation

#29 doc: add Compute Admin GCP Role to SA requirement
  CONTRIBUTING.md
Labels: documentation, enhancement, lgtm

#30 refactor/examples: Reorganize the sample file structure and add sample workloads
  examples/nodeclass/default-gcenodeclass.yaml
  examples/nodeclass/ubuntu-gcenodeclass.yaml
  examples/nodepool/default-nodepool.yaml
  examples/workload/inflate.yaml
Labels: documentation, cleanup

#32 Fix deadlock on instancetype provider List() invokation
  pkg/providers/instancetype/instancetype.go
Labels: bug, cleanup

#34 feat: add GKE instance template metadata resolver to remove conflict label in karpenter.
  pkg/providers/metadata/metadata.go
  pkg/providers/nodepooltemplate/nodepooltemplate.go
Labels: enhancement
